server:
  port: 8093

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

dynamic:
  thread:
    pool:
      enable: true
      host: 127.0.0.1
      port: 6379
      password: 123456
